name: cep
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  convert: ^3.1.2


flutter:

  uses-material-design: true
